# frozen_string_literal: true

class ConvertAuditUuidPksToBigint < ActiveRecord::Migration[8.2]
  def up
    safety_assured do
      remove_audit_foreign_keys
      drop_audit_tables
      recreate_audit_tables
      add_audit_foreign_keys
    end
  end

  def down
    raise ActiveRecord::IrreversibleMigration
  end

  private

  def remove_audit_foreign_keys
    remove_foreign_key(:app_contact_histories, :app_contact_audit_events, column: :event_id, if_exists: true)
    remove_foreign_key(:app_contact_histories, :app_contact_audit_levels, column: :level_id, if_exists: true)
    remove_foreign_key(:app_document_audits, :app_document_audit_events, column: :event_id, if_exists: true)
    remove_foreign_key(:app_document_audits, :app_document_audit_levels, column: :level_id, if_exists: true)
    remove_foreign_key(:app_preference_audits, :app_preference_audit_events, column: :event_id, if_exists: true)
    remove_foreign_key(:app_preference_audits, :app_preference_audit_levels, column: :level_id, if_exists: true)
    remove_foreign_key(:app_timeline_audits, :app_timeline_audit_events, column: :event_id, if_exists: true)
    remove_foreign_key(:app_timeline_audits, :app_timeline_audit_levels, column: :level_id, if_exists: true)
    remove_foreign_key(:com_contact_audits, :com_contact_audit_events, column: :event_id, if_exists: true)
    remove_foreign_key(:com_contact_audits, :com_contact_audit_levels, column: :level_id, if_exists: true)
    remove_foreign_key(:com_document_audits, :com_document_audit_events, column: :event_id, if_exists: true)
    remove_foreign_key(:com_document_audits, :com_document_audit_levels, column: :level_id, if_exists: true)
    remove_foreign_key(:com_preference_audits, :com_preference_audit_events, column: :event_id, if_exists: true)
    remove_foreign_key(:com_preference_audits, :com_preference_audit_levels, column: :level_id, if_exists: true)
    remove_foreign_key(:com_timeline_audits, :com_timeline_audit_events, column: :event_id, if_exists: true)
    remove_foreign_key(:com_timeline_audits, :com_timeline_audit_levels, column: :level_id, if_exists: true)
    remove_foreign_key(:org_contact_histories, :org_contact_audit_events, column: :event_id, if_exists: true)
    remove_foreign_key(:org_contact_histories, :org_contact_audit_levels, column: :level_id, if_exists: true)
    remove_foreign_key(:org_document_audits, :org_document_audit_events, column: :event_id, if_exists: true)
    remove_foreign_key(:org_document_audits, :org_document_audit_levels, column: :level_id, if_exists: true)
    remove_foreign_key(:org_preference_audits, :org_preference_audit_events, column: :event_id, if_exists: true)
    remove_foreign_key(:org_preference_audits, :org_preference_audit_levels, column: :level_id, if_exists: true)
    remove_foreign_key(:org_timeline_audits, :org_timeline_audit_events, column: :event_id, if_exists: true)
    remove_foreign_key(:org_timeline_audits, :org_timeline_audit_levels, column: :level_id, if_exists: true)
    remove_foreign_key(:staff_audits, :staff_audit_events, column: :event_id, if_exists: true)
    remove_foreign_key(:staff_audits, :staff_audit_levels, column: :level_id, if_exists: true)
    remove_foreign_key(:user_audits, :user_audit_events, column: :event_id, if_exists: true)
    remove_foreign_key(:user_audits, :user_audit_levels, column: :level_id, if_exists: true)
  end

  def drop_audit_tables
    drop_table(:app_contact_histories, if_exists: true)
    drop_table(:app_document_audits, if_exists: true)
    drop_table(:app_preference_audits, if_exists: true)
    drop_table(:app_timeline_audits, if_exists: true)
    drop_table(:com_contact_audits, if_exists: true)
    drop_table(:com_document_audits, if_exists: true)
    drop_table(:com_preference_audits, if_exists: true)
    drop_table(:com_timeline_audits, if_exists: true)
    drop_table(:org_contact_histories, if_exists: true)
    drop_table(:org_document_audits, if_exists: true)
    drop_table(:org_preference_audits, if_exists: true)
    drop_table(:org_timeline_audits, if_exists: true)
    drop_table(:staff_audits, if_exists: true)
    drop_table(:user_audits, if_exists: true)
  end

  def recreate_audit_tables
    create_table(:app_contact_histories, id: :bigint) do |t|
      t.bigint(:actor_id, default: 0, null: false)
      t.text(:actor_type, default: "", null: false)
      t.jsonb(:context, default: {}, null: false)
      t.datetime(:created_at, null: false)
      t.text(:current_value, default: "", null: false)
      t.bigint(:event_id, default: 0, null: false)
      t.datetime(:expires_at, default: -> { "(CURRENT_TIMESTAMP + 'P7Y'::interval)" }, null: false)
      t.inet(:ip_address, default: "0.0.0.0", null: false)
      t.bigint(:level_id, default: 0, null: false)
      t.datetime(:occurred_at, default: -> { "CURRENT_TIMESTAMP" }, null: false)
      t.bigint(:parent_id, default: 0, null: false)
      t.integer(:position, default: 0, null: false)
      t.text(:previous_value, default: "", null: false)
      t.bigint(:subject_id, null: false)
      t.text(:subject_type, null: false)
      t.datetime(:updated_at, null: false)
      t.index([:actor_id, :occurred_at], name: "index_app_contact_histories_on_actor_id_and_occurred_at")
      t.index(:event_id, name: "index_app_contact_histories_on_event_id")
      t.index(:expires_at, name: "index_app_contact_histories_on_expires_at")
      t.index(:level_id, name: "index_app_contact_histories_on_level_id")
      t.index(:occurred_at, name: "index_app_contact_histories_on_occurred_at")
      t.index(:parent_id, name: "index_app_contact_histories_on_parent_id")
      t.index(%i(subject_type subject_id occurred_at), name: "idx_on_subject_type_subject_id_occurred_at_21d52ab3f6")
      t.check_constraint("event_id >= 0", name: "app_contact_histories_event_id_non_negative_check")
      t.check_constraint("level_id >= 0", name: "app_contact_histories_level_id_non_negative_check")
    end

    create_table(:app_document_audits, id: :bigint) do |t|
      t.bigint(:actor_id, default: 0, null: false)
      t.text(:actor_type, default: "", null: false)
      t.jsonb(:context, default: {}, null: false)
      t.datetime(:created_at, null: false)
      t.text(:current_value, default: "", null: false)
      t.bigint(:event_id, default: 0, null: false)
      t.datetime(:expires_at, default: -> { "(CURRENT_TIMESTAMP + 'P7Y'::interval)" }, null: false)
      t.inet(:ip_address, default: "0.0.0.0", null: false)
      t.bigint(:level_id, default: 0, null: false)
      t.datetime(:occurred_at, default: -> { "CURRENT_TIMESTAMP" }, null: false)
      t.text(:previous_value, default: "", null: false)
      t.bigint(:subject_id, null: false)
      t.text(:subject_type, null: false)
      t.datetime(:updated_at, null: false)
      t.index([:actor_id, :occurred_at], name: "index_app_document_audits_on_actor_id_and_occurred_at")
      t.index(:event_id, name: "index_app_document_audits_on_event_id")
      t.index(:expires_at, name: "index_app_document_audits_on_expires_at")
      t.index(:level_id, name: "index_app_document_audits_on_level_id")
      t.index(:occurred_at, name: "index_app_document_audits_on_occurred_at")
      t.index(:subject_id, name: "index_app_document_audits_on_subject_id")
      t.index(%i(subject_type subject_id occurred_at), name: "idx_on_subject_type_subject_id_occurred_at_cf1fa79ee4")
      t.check_constraint("event_id >= 0", name: "app_document_audits_event_id_non_negative_check")
      t.check_constraint("level_id >= 0", name: "app_document_audits_level_id_non_negative_check")
    end

    create_table(:app_preference_audits, id: :bigint) do |t|
      t.bigint(:actor_id, default: 0, null: false)
      t.text(:actor_type, default: "", null: false)
      t.jsonb(:context, default: {}, null: false)
      t.datetime(:created_at, null: false)
      t.text(:current_value, default: "", null: false)
      t.bigint(:event_id, default: 0, null: false)
      t.datetime(:expires_at, default: -> { "(CURRENT_TIMESTAMP + 'P7Y'::interval)" }, null: false)
      t.inet(:ip_address, default: "0.0.0.0", null: false)
      t.bigint(:level_id, default: 0, null: false)
      t.datetime(:occurred_at, default: -> { "CURRENT_TIMESTAMP" }, null: false)
      t.text(:previous_value, default: "", null: false)
      t.bigint(:subject_id, null: false)
      t.text(:subject_type, null: false)
      t.datetime(:updated_at, null: false)
      t.index([:actor_id, :occurred_at], name: "index_app_preference_audits_on_actor_id_and_occurred_at")
      t.index(:event_id, name: "index_app_preference_audits_on_event_id")
      t.index(:expires_at, name: "index_app_preference_audits_on_expires_at")
      t.index(:level_id, name: "index_app_preference_audits_on_level_id")
      t.index(:occurred_at, name: "index_app_preference_audits_on_occurred_at")
      t.index(:subject_id, name: "index_app_preference_audits_on_subject_id")
      t.index(%i(subject_type subject_id occurred_at), name: "idx_on_subject_type_subject_id_occurred_at_app_pref")
      t.check_constraint("event_id >= 0", name: "app_preference_audits_event_id_non_negative_check")
      t.check_constraint("level_id >= 0", name: "app_preference_audits_level_id_non_negative_check")
    end

    create_table(:app_timeline_audits, id: :bigint) do |t|
      t.bigint(:actor_id, default: 0, null: false)
      t.text(:actor_type, default: "", null: false)
      t.jsonb(:context, default: {}, null: false)
      t.datetime(:created_at, null: false)
      t.text(:current_value, default: "", null: false)
      t.bigint(:event_id, default: 0, null: false)
      t.datetime(:expires_at, default: -> { "(CURRENT_TIMESTAMP + 'P7Y'::interval)" }, null: false)
      t.inet(:ip_address, default: "0.0.0.0", null: false)
      t.bigint(:level_id, default: 0, null: false)
      t.datetime(:occurred_at, default: -> { "CURRENT_TIMESTAMP" }, null: false)
      t.text(:previous_value, default: "", null: false)
      t.bigint(:subject_id, null: false)
      t.text(:subject_type, null: false)
      t.datetime(:updated_at, null: false)
      t.index([:actor_id, :occurred_at], name: "index_app_timeline_audits_on_actor_id_and_occurred_at")
      t.index(:event_id, name: "index_app_timeline_audits_on_event_id")
      t.index(:expires_at, name: "index_app_timeline_audits_on_expires_at")
      t.index(:level_id, name: "index_app_timeline_audits_on_level_id")
      t.index(:occurred_at, name: "index_app_timeline_audits_on_occurred_at")
      t.index(:subject_id, name: "index_app_timeline_audits_on_subject_id")
      t.index(%i(subject_type subject_id occurred_at), name: "idx_on_subject_type_subject_id_occurred_at_c80b4e4f83")
      t.check_constraint("event_id >= 0", name: "app_timeline_audits_event_id_non_negative_check")
      t.check_constraint("level_id >= 0", name: "app_timeline_audits_level_id_non_negative_check")
    end

    create_table(:com_contact_audits, id: :bigint) do |t|
      t.bigint(:actor_id, default: 0, null: false)
      t.text(:actor_type, default: "", null: false)
      t.jsonb(:context, default: {}, null: false)
      t.datetime(:created_at, null: false)
      t.text(:current_value, default: "", null: false)
      t.bigint(:event_id, default: 0, null: false)
      t.datetime(:expires_at, default: -> { "(CURRENT_TIMESTAMP + 'P7Y'::interval)" }, null: false)
      t.inet(:ip_address, default: "0.0.0.0", null: false)
      t.bigint(:level_id, default: 0, null: false)
      t.datetime(:occurred_at, default: -> { "CURRENT_TIMESTAMP" }, null: false)
      t.bigint(:parent_id, default: 0, null: false)
      t.integer(:position, default: 0, null: false)
      t.text(:previous_value, default: "", null: false)
      t.bigint(:subject_id, null: false)
      t.text(:subject_type, null: false)
      t.datetime(:updated_at, null: false)
      t.index([:actor_id, :occurred_at], name: "index_com_contact_audits_on_actor_id_and_occurred_at")
      t.index(:event_id, name: "index_com_contact_audits_on_event_id")
      t.index(:expires_at, name: "index_com_contact_audits_on_expires_at")
      t.index(:level_id, name: "index_com_contact_audits_on_level_id")
      t.index(:occurred_at, name: "index_com_contact_audits_on_occurred_at")
      t.index(:parent_id, name: "index_com_contact_audits_on_parent_id")
      t.index(%i(subject_type subject_id occurred_at), name: "idx_on_subject_type_subject_id_occurred_at_1ec6aec32c")
      t.check_constraint("event_id >= 0", name: "com_contact_audits_event_id_non_negative_check")
      t.check_constraint("level_id >= 0", name: "com_contact_audits_level_id_non_negative_check")
    end

    create_table(:com_document_audits, id: :bigint) do |t|
      t.bigint(:actor_id, default: 0, null: false)
      t.text(:actor_type, default: "", null: false)
      t.jsonb(:context, default: {}, null: false)
      t.datetime(:created_at, null: false)
      t.text(:current_value, default: "", null: false)
      t.bigint(:event_id, default: 0, null: false)
      t.datetime(:expires_at, default: -> { "(CURRENT_TIMESTAMP + 'P7Y'::interval)" }, null: false)
      t.inet(:ip_address, default: "0.0.0.0", null: false)
      t.bigint(:level_id, default: 0, null: false)
      t.datetime(:occurred_at, default: -> { "CURRENT_TIMESTAMP" }, null: false)
      t.text(:previous_value, default: "", null: false)
      t.bigint(:subject_id, null: false)
      t.text(:subject_type, null: false)
      t.datetime(:updated_at, null: false)
      t.index([:actor_id, :occurred_at], name: "index_com_document_audits_on_actor_id_and_occurred_at")
      t.index(:event_id, name: "index_com_document_audits_on_event_id")
      t.index(:expires_at, name: "index_com_document_audits_on_expires_at")
      t.index(:level_id, name: "index_com_document_audits_on_level_id")
      t.index(:occurred_at, name: "index_com_document_audits_on_occurred_at")
      t.index(:subject_id, name: "index_com_document_audits_on_subject_id")
      t.index(%i(subject_type subject_id occurred_at), name: "idx_on_subject_type_subject_id_occurred_at_c40361e81b")
      t.check_constraint("event_id >= 0", name: "com_document_audits_event_id_non_negative_check")
      t.check_constraint("level_id >= 0", name: "com_document_audits_level_id_non_negative_check")
    end

    create_table(:com_preference_audits, id: :bigint) do |t|
      t.bigint(:actor_id, default: 0, null: false)
      t.text(:actor_type, default: "", null: false)
      t.jsonb(:context, default: {}, null: false)
      t.datetime(:created_at, null: false)
      t.text(:current_value, default: "", null: false)
      t.bigint(:event_id, default: 0, null: false)
      t.datetime(:expires_at, default: -> { "(CURRENT_TIMESTAMP + 'P7Y'::interval)" }, null: false)
      t.inet(:ip_address, default: "0.0.0.0", null: false)
      t.bigint(:level_id, default: 0, null: false)
      t.datetime(:occurred_at, default: -> { "CURRENT_TIMESTAMP" }, null: false)
      t.text(:previous_value, default: "", null: false)
      t.bigint(:subject_id, null: false)
      t.text(:subject_type, null: false)
      t.datetime(:updated_at, null: false)
      t.index([:actor_id, :occurred_at], name: "index_com_preference_audits_on_actor_id_and_occurred_at")
      t.index(:event_id, name: "index_com_preference_audits_on_event_id")
      t.index(:expires_at, name: "index_com_preference_audits_on_expires_at")
      t.index(:level_id, name: "index_com_preference_audits_on_level_id")
      t.index(:occurred_at, name: "index_com_preference_audits_on_occurred_at")
      t.index(:subject_id, name: "index_com_preference_audits_on_subject_id")
      t.index(%i(subject_type subject_id occurred_at), name: "idx_on_subject_type_subject_id_occurred_at_com_pref")
      t.check_constraint("event_id >= 0", name: "com_preference_audits_event_id_non_negative_check")
      t.check_constraint("level_id >= 0", name: "com_preference_audits_level_id_non_negative_check")
    end

    create_table(:com_timeline_audits, id: :bigint) do |t|
      t.bigint(:actor_id, default: 0, null: false)
      t.text(:actor_type, default: "", null: false)
      t.jsonb(:context, default: {}, null: false)
      t.datetime(:created_at, null: false)
      t.text(:current_value, default: "", null: false)
      t.bigint(:event_id, default: 0, null: false)
      t.datetime(:expires_at, default: -> { "(CURRENT_TIMESTAMP + 'P7Y'::interval)" }, null: false)
      t.inet(:ip_address, default: "0.0.0.0", null: false)
      t.bigint(:level_id, default: 0, null: false)
      t.datetime(:occurred_at, default: -> { "CURRENT_TIMESTAMP" }, null: false)
      t.text(:previous_value, default: "", null: false)
      t.bigint(:subject_id, null: false)
      t.text(:subject_type, null: false)
      t.datetime(:updated_at, null: false)
      t.index([:actor_id, :occurred_at], name: "index_com_timeline_audits_on_actor_id_and_occurred_at")
      t.index(:event_id, name: "index_com_timeline_audits_on_event_id")
      t.index(:expires_at, name: "index_com_timeline_audits_on_expires_at")
      t.index(:level_id, name: "index_com_timeline_audits_on_level_id")
      t.index(:occurred_at, name: "index_com_timeline_audits_on_occurred_at")
      t.index(:subject_id, name: "index_com_timeline_audits_on_subject_id")
      t.index(%i(subject_type subject_id occurred_at), name: "idx_on_subject_type_subject_id_occurred_at_99ec847a5c")
      t.check_constraint("event_id >= 0", name: "com_timeline_audits_event_id_non_negative_check")
      t.check_constraint("level_id >= 0", name: "com_timeline_audits_level_id_non_negative_check")
    end

    create_table(:org_contact_histories, id: :bigint) do |t|
      t.bigint(:actor_id, default: 0, null: false)
      t.text(:actor_type, default: "", null: false)
      t.jsonb(:context, default: {}, null: false)
      t.datetime(:created_at, null: false)
      t.text(:current_value, default: "", null: false)
      t.bigint(:event_id, default: 0, null: false)
      t.datetime(:expires_at, default: -> { "(CURRENT_TIMESTAMP + 'P7Y'::interval)" }, null: false)
      t.inet(:ip_address, default: "0.0.0.0", null: false)
      t.bigint(:level_id, default: 0, null: false)
      t.datetime(:occurred_at, default: -> { "CURRENT_TIMESTAMP" }, null: false)
      t.bigint(:parent_id, default: 0, null: false)
      t.integer(:position, default: 0, null: false)
      t.text(:previous_value, default: "", null: false)
      t.bigint(:subject_id, null: false)
      t.text(:subject_type, null: false)
      t.datetime(:updated_at, null: false)
      t.index([:actor_id, :occurred_at], name: "index_org_contact_histories_on_actor_id_and_occurred_at")
      t.index(:event_id, name: "index_org_contact_histories_on_event_id")
      t.index(:expires_at, name: "index_org_contact_histories_on_expires_at")
      t.index(:level_id, name: "index_org_contact_histories_on_level_id")
      t.index(:occurred_at, name: "index_org_contact_histories_on_occurred_at")
      t.index(:parent_id, name: "index_org_contact_histories_on_parent_id")
      t.index(%i(subject_type subject_id occurred_at), name: "idx_on_subject_type_subject_id_occurred_at_3eb778d373")
      t.check_constraint("event_id >= 0", name: "org_contact_histories_event_id_non_negative_check")
      t.check_constraint("level_id >= 0", name: "org_contact_histories_level_id_non_negative_check")
    end

    create_table(:org_document_audits, id: :bigint) do |t|
      t.bigint(:actor_id, default: 0, null: false)
      t.text(:actor_type, default: "", null: false)
      t.jsonb(:context, default: {}, null: false)
      t.datetime(:created_at, null: false)
      t.text(:current_value, default: "", null: false)
      t.bigint(:event_id, default: 0, null: false)
      t.datetime(:expires_at, default: -> { "(CURRENT_TIMESTAMP + 'P7Y'::interval)" }, null: false)
      t.inet(:ip_address, default: "0.0.0.0", null: false)
      t.bigint(:level_id, default: 0, null: false)
      t.datetime(:occurred_at, default: -> { "CURRENT_TIMESTAMP" }, null: false)
      t.text(:previous_value, default: "", null: false)
      t.bigint(:subject_id, null: false)
      t.text(:subject_type, null: false)
      t.datetime(:updated_at, null: false)
      t.index([:actor_id, :occurred_at], name: "index_org_document_audits_on_actor_id_and_occurred_at")
      t.index(:event_id, name: "index_org_document_audits_on_event_id")
      t.index(:expires_at, name: "index_org_document_audits_on_expires_at")
      t.index(:level_id, name: "index_org_document_audits_on_level_id")
      t.index(:occurred_at, name: "index_org_document_audits_on_occurred_at")
      t.index(:subject_id, name: "index_org_document_audits_on_subject_id")
      t.index(%i(subject_type subject_id occurred_at), name: "idx_on_subject_type_subject_id_occurred_at_bf53171ad0")
      t.check_constraint("event_id >= 0", name: "org_document_audits_event_id_non_negative_check")
      t.check_constraint("level_id >= 0", name: "org_document_audits_level_id_non_negative_check")
    end

    create_table(:org_preference_audits, id: :bigint) do |t|
      t.bigint(:actor_id, default: 0, null: false)
      t.text(:actor_type, default: "", null: false)
      t.jsonb(:context, default: {}, null: false)
      t.datetime(:created_at, null: false)
      t.text(:current_value, default: "", null: false)
      t.bigint(:event_id, default: 0, null: false)
      t.datetime(:expires_at, default: -> { "(CURRENT_TIMESTAMP + 'P7Y'::interval)" }, null: false)
      t.inet(:ip_address, default: "0.0.0.0", null: false)
      t.bigint(:level_id, default: 0, null: false)
      t.datetime(:occurred_at, default: -> { "CURRENT_TIMESTAMP" }, null: false)
      t.text(:previous_value, default: "", null: false)
      t.bigint(:subject_id, null: false)
      t.text(:subject_type, null: false)
      t.datetime(:updated_at, null: false)
      t.index([:actor_id, :occurred_at], name: "index_org_preference_audits_on_actor_id_and_occurred_at")
      t.index(:event_id, name: "index_org_preference_audits_on_event_id")
      t.index(:expires_at, name: "index_org_preference_audits_on_expires_at")
      t.index(:level_id, name: "index_org_preference_audits_on_level_id")
      t.index(:occurred_at, name: "index_org_preference_audits_on_occurred_at")
      t.index(:subject_id, name: "index_org_preference_audits_on_subject_id")
      t.index(%i(subject_type subject_id occurred_at), name: "idx_on_subject_type_subject_id_occurred_at_org_pref")
      t.check_constraint("event_id >= 0", name: "org_preference_audits_event_id_non_negative_check")
      t.check_constraint("level_id >= 0", name: "org_preference_audits_level_id_non_negative_check")
    end

    create_table(:org_timeline_audits, id: :bigint) do |t|
      t.bigint(:actor_id, default: 0, null: false)
      t.text(:actor_type, default: "", null: false)
      t.jsonb(:context, default: {}, null: false)
      t.datetime(:created_at, null: false)
      t.text(:current_value, default: "", null: false)
      t.bigint(:event_id, default: 0, null: false)
      t.datetime(:expires_at, default: -> { "(CURRENT_TIMESTAMP + 'P7Y'::interval)" }, null: false)
      t.inet(:ip_address, default: "0.0.0.0", null: false)
      t.bigint(:level_id, default: 0, null: false)
      t.datetime(:occurred_at, default: -> { "CURRENT_TIMESTAMP" }, null: false)
      t.text(:previous_value, default: "", null: false)
      t.bigint(:subject_id, null: false)
      t.text(:subject_type, null: false)
      t.datetime(:updated_at, null: false)
      t.index([:actor_id, :occurred_at], name: "index_org_timeline_audits_on_actor_id_and_occurred_at")
      t.index(:event_id, name: "index_org_timeline_audits_on_event_id")
      t.index(:expires_at, name: "index_org_timeline_audits_on_expires_at")
      t.index(:level_id, name: "index_org_timeline_audits_on_level_id")
      t.index(:occurred_at, name: "index_org_timeline_audits_on_occurred_at")
      t.index(:subject_id, name: "index_org_timeline_audits_on_subject_id")
      t.index(%i(subject_type subject_id occurred_at), name: "idx_on_subject_type_subject_id_occurred_at_0f4341deba")
      t.check_constraint("event_id >= 0", name: "org_timeline_audits_event_id_non_negative_check")
      t.check_constraint("level_id >= 0", name: "org_timeline_audits_level_id_non_negative_check")
    end

    create_table(:staff_audits, id: :bigint) do |t|
      t.bigint(:actor_id, default: 0, null: false)
      t.text(:actor_type, default: "", null: false)
      t.jsonb(:context, default: {}, null: false)
      t.datetime(:created_at, null: false)
      t.text(:current_value, default: "", null: false)
      t.bigint(:event_id, default: 0, null: false)
      t.datetime(:expires_at, default: -> { "(CURRENT_TIMESTAMP + 'P7Y'::interval)" }, null: false)
      t.inet(:ip_address, default: "0.0.0.0", null: false)
      t.bigint(:level_id, default: 0, null: false)
      t.datetime(:occurred_at, default: -> { "CURRENT_TIMESTAMP" }, null: false)
      t.text(:previous_value, default: "", null: false)
      t.bigint(:subject_id, null: false)
      t.text(:subject_type, null: false)
      t.datetime(:updated_at, null: false)
      t.index([:actor_id, :occurred_at], name: "index_staff_identity_audits_on_actor_id_and_occurred_at")
      t.index([:actor_type, :actor_id], name: "index_staff_identity_audits_on_actor")
      t.index(:event_id, name: "index_staff_audits_on_event_id")
      t.index(:expires_at, name: "index_staff_identity_audits_on_expires_at")
      t.index(:level_id, name: "index_staff_audits_on_level_id")
      t.index(:occurred_at, name: "index_staff_identity_audits_on_occurred_at")
      t.index(:subject_id, name: "index_staff_identity_audits_on_subject_id")
      t.index(%i(subject_type subject_id occurred_at), name: "idx_on_subject_type_subject_id_occurred_at_2e96c29236")
      t.check_constraint("event_id >= 0", name: "staff_audits_event_id_non_negative_check")
      t.check_constraint("level_id >= 0", name: "staff_audits_level_id_non_negative_check")
    end

    create_table(:user_audits, id: :bigint) do |t|
      t.bigint(:actor_id, default: 0, null: false)
      t.text(:actor_type, default: "", null: false)
      t.jsonb(:context, default: {}, null: false)
      t.datetime(:created_at, null: false)
      t.text(:current_value, default: "", null: false)
      t.bigint(:event_id, default: 0, null: false)
      t.datetime(:expires_at, default: -> { "(CURRENT_TIMESTAMP + 'P7Y'::interval)" }, null: false)
      t.inet(:ip_address, default: "0.0.0.0", null: false)
      t.bigint(:level_id, default: 0, null: false)
      t.datetime(:occurred_at, default: -> { "CURRENT_TIMESTAMP" }, null: false)
      t.text(:previous_value, default: "", null: false)
      t.bigint(:subject_id, null: false)
      t.text(:subject_type, null: false)
      t.datetime(:updated_at, null: false)
      t.index([:actor_id, :occurred_at], name: "index_user_identity_audits_on_actor_id_and_occurred_at")
      t.index([:actor_type, :actor_id], name: "index_user_identity_audits_on_actor")
      t.index(:event_id, name: "index_user_audits_on_event_id")
      t.index(:expires_at, name: "index_user_identity_audits_on_expires_at")
      t.index(:level_id, name: "index_user_audits_on_level_id")
      t.index(:occurred_at, name: "index_user_identity_audits_on_occurred_at")
      t.index(:subject_id, name: "index_user_identity_audits_on_subject_id")
      t.index(%i(subject_type subject_id occurred_at), name: "idx_on_subject_type_subject_id_occurred_at_a29eb711dd")
      t.check_constraint("event_id >= 0", name: "user_audits_event_id_non_negative_check")
      t.check_constraint("level_id >= 0", name: "user_audits_level_id_non_negative_check")
    end
  end

  def add_audit_foreign_keys
    add_foreign_key(:app_contact_histories, :app_contact_audit_events, column: :event_id)
    add_foreign_key(:app_contact_histories, :app_contact_audit_levels, column: :level_id)
    add_foreign_key(:app_document_audits, :app_document_audit_events, column: :event_id)
    add_foreign_key(:app_document_audits, :app_document_audit_levels, column: :level_id)
    add_foreign_key(:app_preference_audits, :app_preference_audit_events, column: :event_id)
    add_foreign_key(:app_preference_audits, :app_preference_audit_levels, column: :level_id)
    add_foreign_key(:app_timeline_audits, :app_timeline_audit_events, column: :event_id)
    add_foreign_key(:app_timeline_audits, :app_timeline_audit_levels, column: :level_id)
    add_foreign_key(:com_contact_audits, :com_contact_audit_events, column: :event_id)
    add_foreign_key(:com_contact_audits, :com_contact_audit_levels, column: :level_id)
    add_foreign_key(:com_document_audits, :com_document_audit_events, column: :event_id)
    add_foreign_key(:com_document_audits, :com_document_audit_levels, column: :level_id)
    add_foreign_key(:com_preference_audits, :com_preference_audit_events, column: :event_id)
    add_foreign_key(:com_preference_audits, :com_preference_audit_levels, column: :level_id)
    add_foreign_key(:com_timeline_audits, :com_timeline_audit_events, column: :event_id)
    add_foreign_key(:com_timeline_audits, :com_timeline_audit_levels, column: :level_id)
    add_foreign_key(:org_contact_histories, :org_contact_audit_events, column: :event_id)
    add_foreign_key(:org_contact_histories, :org_contact_audit_levels, column: :level_id)
    add_foreign_key(:org_document_audits, :org_document_audit_events, column: :event_id)
    add_foreign_key(:org_document_audits, :org_document_audit_levels, column: :level_id)
    add_foreign_key(:org_preference_audits, :org_preference_audit_events, column: :event_id)
    add_foreign_key(:org_preference_audits, :org_preference_audit_levels, column: :level_id)
    add_foreign_key(:org_timeline_audits, :org_timeline_audit_events, column: :event_id)
    add_foreign_key(:org_timeline_audits, :org_timeline_audit_levels, column: :level_id)
    add_foreign_key(:staff_audits, :staff_audit_events, column: :event_id)
    add_foreign_key(:staff_audits, :staff_audit_levels, column: :level_id)
    add_foreign_key(:user_audits, :user_audit_events, column: :event_id)
    add_foreign_key(:user_audits, :user_audit_levels, column: :level_id)
  end
end
