# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/concurrent-ruby/all/concurrent-ruby.rbi
#
# concurrent-ruby-1.3.6

module Concurrent
  def abort_transaction; end
  def atomically; end
  def call_dataflow(method, executor, *inputs, &block); end
  def dataflow!(*inputs, &block); end
  def dataflow(*inputs, &block); end
  def dataflow_with!(executor, *inputs, &block); end
  def dataflow_with(executor, *inputs, &block); end
  def leave_transaction; end
  def monotonic_time(unit = nil); end
  def self.abort_transaction; end
  def self.atomically; end
  def self.available_processor_count; end
  def self.call_dataflow(method, executor, *inputs, &block); end
  def self.cpu_quota; end
  def self.cpu_shares; end
  def self.create_simple_logger(level = nil, output = nil); end
  def self.create_stdlib_logger(level = nil, output = nil); end
  def self.dataflow!(*inputs, &block); end
  def self.dataflow(*inputs, &block); end
  def self.dataflow_with!(executor, *inputs, &block); end
  def self.dataflow_with(executor, *inputs, &block); end
  def self.disable_at_exit_handlers!; end
  def self.executor(executor_identifier); end
  def self.global_fast_executor; end
  def self.global_immediate_executor; end
  def self.global_io_executor; end
  def self.global_logger; end
  def self.global_logger=(value); end
  def self.global_timer_set; end
  def self.leave_transaction; end
  def self.monotonic_time(unit = nil); end
  def self.mutex_owned_per_thread?; end
  def self.new_fast_executor(opts = nil); end
  def self.new_io_executor(opts = nil); end
  def self.physical_processor_count; end
  def self.processor_count; end
  def self.processor_counter; end
  def self.use_simple_logger(level = nil, output = nil); end
  def self.use_stdlib_logger(level = nil, output = nil); end
  extend Concurrent::Concern::Deprecation
  extend Concurrent::Concern::Logging
  extend Concurrent::Utility::EngineDetector
  extend Concurrent::Utility::NativeExtensionLoader
end
module Concurrent::Utility
end
module Concurrent::Utility::EngineDetector
  def on_cruby?; end
  def on_jruby?; end
  def on_linux?; end
  def on_osx?; end
  def on_truffleruby?; end
  def on_windows?; end
  def ruby_version(version = nil, comparison, major, minor, patch); end
end
module Concurrent::Collection
end
class Concurrent::Collection::NonConcurrentMapBackend
  def [](key); end
  def []=(key, value); end
  def clear; end
  def compute(key); end
  def compute_if_absent(key); end
  def compute_if_present(key); end
  def delete(key); end
  def delete_pair(key, value); end
  def dupped_backend; end
  def each_pair; end
  def get_and_set(key, value); end
  def get_or_default(key, default_value); end
  def initialize(options = nil, &default_proc); end
  def initialize_copy(other); end
  def key?(key); end
  def merge_pair(key, value); end
  def pair?(key, expected_value); end
  def replace_if_exists(key, new_value); end
  def replace_pair(key, old_value, new_value); end
  def set_backend(default_proc); end
  def size; end
  def store_computed_value(key, new_value); end
end
class Concurrent::Collection::MriMapBackend < Concurrent::Collection::NonConcurrentMapBackend
  def []=(key, value); end
  def clear; end
  def compute(key); end
  def compute_if_absent(key); end
  def compute_if_present(key); end
  def delete(key); end
  def delete_pair(key, value); end
  def get_and_set(key, value); end
  def initialize(options = nil, &default_proc); end
  def merge_pair(key, value); end
  def replace_if_exists(key, new_value); end
  def replace_pair(key, old_value, new_value); end
end
class Concurrent::Map < Concurrent::Collection::MriMapBackend
  def each; end
  def each_key; end
  def each_pair; end
  def each_value; end
  def empty?; end
  def fetch(key, default_value = nil); end
  def fetch_or_store(key, default_value = nil); end
  def get(key); end
  def initialize_copy(other); end
  def inspect; end
  def key(value); end
  def keys; end
  def marshal_dump; end
  def marshal_load(hash); end
  def populate_from(hash); end
  def put(key, value); end
  def put_if_absent(key, value); end
  def raise_fetch_no_key; end
  def validate_options_hash!(options); end
  def value?(value); end
  def values; end
end
module Concurrent::ThreadSafe
end
module Concurrent::ThreadSafe::Util
  def self.make_synchronized_on_cruby(klass); end
  def self.make_synchronized_on_truffleruby(klass); end
end
class Concurrent::Hash < Hash
end
class Concurrent::AbstractLocals
  def fetch(index); end
  def free_index(index); end
  def initialize; end
  def local_finalizer(index); end
  def locals!; end
  def locals; end
  def next_index(local); end
  def set(index, value); end
  def synchronize; end
  def thread_fiber_finalizer(array_object_id); end
  def weak_synchronize; end
end
class Concurrent::ThreadLocals < Concurrent::AbstractLocals
  def locals!; end
  def locals; end
end
class Concurrent::FiberLocals < Concurrent::AbstractLocals
  def locals!; end
  def locals; end
end
class Concurrent::ThreadLocalVar
  def bind(value); end
  def default; end
  def initialize(default = nil, &default_block); end
  def value; end
  def value=(value); end
end
class Concurrent::Error < StandardError
end
class Concurrent::ConfigurationError < Concurrent::Error
end
class Concurrent::CancelledOperationError < Concurrent::Error
end
class Concurrent::LifecycleError < Concurrent::Error
end
class Concurrent::ImmutabilityError < Concurrent::Error
end
class Concurrent::IllegalOperationError < Concurrent::Error
end
class Concurrent::InitializationError < Concurrent::Error
end
class Concurrent::MaxRestartFrequencyError < Concurrent::Error
end
class Concurrent::MultipleAssignmentError < Concurrent::Error
  def initialize(message = nil, inspection_data = nil); end
  def inspect; end
  def inspection_data; end
end
class Concurrent::RejectedExecutionError < Concurrent::Error
end
class Concurrent::ResourceLimitError < Concurrent::Error
end
class Concurrent::TimeoutError < Concurrent::Error
end
class Concurrent::MultipleErrors < Concurrent::Error
  def errors; end
  def initialize(errors, message = nil); end
end
class Concurrent::ConcurrentUpdateError < ThreadError
end
module Concurrent::Synchronization
  def self.full_memory_barrier; end
end
class Concurrent::Synchronization::AbstractObject
  def full_memory_barrier; end
  def initialize; end
  def self.attr_volatile(*names); end
end
module Concurrent::Utility::NativeExtensionLoader
  def allow_c_extensions?; end
  def c_extensions_loaded?; end
  def java_extensions_loaded?; end
  def load_error_path(error); end
  def load_native_extensions; end
  def set_c_extensions_loaded; end
  def set_java_extensions_loaded; end
  def try_load_c_extension(path); end
end
module Concurrent::Synchronization::SafeInitialization
  def new(*args, &block); end
end
module Concurrent::Synchronization::Volatile
  def full_memory_barrier; end
  def self.included(base); end
end
module Concurrent::Synchronization::Volatile::ClassMethods
  def attr_volatile(*names); end
end
module Concurrent::AtomicDirectUpdate
  def try_update!; end
  def try_update; end
  def update; end
end
module Concurrent::AtomicNumericCompareAndSetWrapper
  def compare_and_set(old_value, new_value); end
end
class Concurrent::MutexAtomicReference
  def _compare_and_set(old_value, new_value); end
  def compare_and_swap(old_value, new_value); end
  def get; end
  def get_and_set(new_value); end
  def initialize(value = nil); end
  def set(new_value); end
  def swap(new_value); end
  def synchronize; end
  def value; end
  def value=(new_value); end
  extend Concurrent::Synchronization::SafeInitialization
  include Concurrent::AtomicDirectUpdate
  include Concurrent::AtomicNumericCompareAndSetWrapper
end
class Concurrent::AtomicReference < Concurrent::MutexAtomicReference
  def inspect; end
  def to_s; end
end
class Concurrent::Synchronization::Object < Concurrent::Synchronization::AbstractObject
  def __initialize_atomic_fields__; end
  def initialize; end
  def self.atomic_attribute?(name); end
  def self.atomic_attributes(inherited = nil); end
  def self.attr_atomic(*names); end
  def self.define_initialize_atomic_fields; end
  def self.ensure_safe_initialization_when_final_fields_are_present; end
  def self.safe_initialization!; end
  def self.safe_initialization?; end
  extend Concurrent::Synchronization::Volatile::ClassMethods
  include Concurrent::Synchronization::Volatile
end
class Concurrent::Synchronization::AbstractLockableObject < Concurrent::Synchronization::Object
  def ns_broadcast; end
  def ns_signal; end
  def ns_wait(timeout = nil); end
  def ns_wait_until(timeout = nil, &condition); end
  def synchronize; end
end
module Concurrent::Synchronization::ConditionSignalling
  def ns_broadcast; end
  def ns_signal; end
end
class Concurrent::Synchronization::MutexLockableObject < Concurrent::Synchronization::AbstractLockableObject
  def initialize; end
  def initialize_copy(other); end
  def ns_wait(timeout = nil); end
  def synchronize; end
  extend Concurrent::Synchronization::SafeInitialization
  include Concurrent::Synchronization::ConditionSignalling
end
class Concurrent::Synchronization::MonitorLockableObject < Concurrent::Synchronization::AbstractLockableObject
  def initialize; end
  def initialize_copy(other); end
  def ns_wait(timeout = nil); end
  def synchronize; end
  extend Concurrent::Synchronization::SafeInitialization
  include Concurrent::Synchronization::ConditionSignalling
end
class Concurrent::Synchronization::LockableObject < Concurrent::Synchronization::MutexLockableObject
  def new_condition; end
end
class Concurrent::Event < Concurrent::Synchronization::LockableObject
  def initialize; end
  def ns_initialize; end
  def ns_set; end
  def reset; end
  def set; end
  def set?; end
  def try?; end
  def wait(timeout = nil); end
end
module Concurrent::Concern
end
module Concurrent::Concern::Dereferenceable
  def apply_deref_options(value); end
  def deref; end
  def ns_set_deref_options(opts); end
  def set_deref_options(opts = nil); end
  def value; end
  def value=(value); end
end
module Concurrent::Concern::Obligation
  def compare_and_set_state(next_state, *expected_current); end
  def complete?; end
  def event; end
  def exception(*args); end
  def fulfilled?; end
  def get_arguments_from(opts = nil); end
  def if_state(*expected_states); end
  def incomplete?; end
  def init_obligation; end
  def no_error!(timeout = nil); end
  def ns_check_state?(expected); end
  def ns_set_state(value); end
  def pending?; end
  def realized?; end
  def reason; end
  def rejected?; end
  def set_state(success, value, reason); end
  def state; end
  def state=(value); end
  def unscheduled?; end
  def value!(timeout = nil); end
  def value(timeout = nil); end
  def wait!(timeout = nil); end
  def wait(timeout = nil); end
  include Concurrent::Concern::Dereferenceable
end
module Concurrent::Concern::Logging
  def log(level, progname, message = nil, &block); end
end
module Concurrent::Concern::Deprecation
  def deprecated(message, strip = nil); end
  def deprecated_method(old_name, new_name); end
  extend Concurrent::Concern::Deprecation
  include Concurrent::Concern::Logging
end
module Concurrent::ExecutorService
  def <<(task); end
  def can_overflow?; end
  def post(*args, &task); end
  def serialized?; end
  include Concurrent::Concern::Logging
end
class Concurrent::AbstractExecutorService < Concurrent::Synchronization::LockableObject
  def auto_terminate=(value); end
  def auto_terminate?; end
  def fallback_action(*args); end
  def fallback_policy; end
  def initialize(opts = nil, &block); end
  def kill; end
  def name; end
  def ns_auto_terminate?; end
  def ns_execute(*args, &task); end
  def ns_kill_execution; end
  def ns_shutdown_execution; end
  def running?; end
  def shutdown; end
  def shutdown?; end
  def shuttingdown?; end
  def to_s; end
  def wait_for_termination(timeout = nil); end
  include Concurrent::Concern::Deprecation
  include Concurrent::ExecutorService
end
module Concurrent::SerialExecutorService
  def serialized?; end
  include Concurrent::ExecutorService
end
class Concurrent::ImmediateExecutor < Concurrent::AbstractExecutorService
  def <<(task); end
  def initialize; end
  def kill; end
  def post(*args, &task); end
  def running?; end
  def shutdown; end
  def shutdown?; end
  def shuttingdown?; end
  def wait_for_termination(timeout = nil); end
  include Concurrent::SerialExecutorService
end
class Concurrent::Delay < Concurrent::Synchronization::LockableObject
  def execute_task_once; end
  def initialize(opts = nil, &block); end
  def ns_initialize(opts, &block); end
  def reconfigure(&block); end
  def value!(timeout = nil); end
  def value(timeout = nil); end
  def wait(timeout = nil); end
  include Concurrent::Concern::Obligation
end
class Concurrent::RubyExecutorService < Concurrent::AbstractExecutorService
  def initialize(*args, &block); end
  def kill; end
  def ns_running?; end
  def ns_shutdown?; end
  def ns_shutdown_execution; end
  def ns_shuttingdown?; end
  def post(*args, &task); end
  def shutdown; end
  def stop_event; end
  def stopped_event; end
  def wait_for_termination(timeout = nil); end
end
class Concurrent::Collection::TimeoutQueue < Thread::Queue
end
class Concurrent::RubyThreadPoolExecutor < Concurrent::RubyExecutorService
  def active_count; end
  def can_overflow?; end
  def completed_task_count; end
  def idletime; end
  def initialize(opts = nil); end
  def largest_length; end
  def length; end
  def max_length; end
  def max_queue; end
  def min_length; end
  def ns_add_busy_worker; end
  def ns_assign_worker(*args, &task); end
  def ns_enqueue(*args, &task); end
  def ns_execute(*args, &task); end
  def ns_initialize(opts); end
  def ns_kill_execution; end
  def ns_limited_queue?; end
  def ns_prunable_capacity; end
  def ns_ready_worker(worker, last_message, success = nil); end
  def ns_remove_busy_worker(worker); end
  def ns_remove_ready_worker(worker); end
  def ns_reset_if_forked; end
  def ns_shutdown_execution; end
  def ns_worker_died(worker); end
  def prune_pool; end
  def prune_worker(worker); end
  def queue_length; end
  def ready_worker(worker, last_message); end
  def remaining_capacity; end
  def remove_worker(worker); end
  def scheduled_task_count; end
  def synchronous; end
  def worker_died(worker); end
  def worker_task_completed; end
  include Concurrent::Concern::Deprecation
end
class Concurrent::RubyThreadPoolExecutor::Worker
  def <<(message); end
  def create_worker(queue, pool, idletime); end
  def initialize(pool, id); end
  def kill; end
  def run_task(pool, task, args); end
  def stop; end
  include Concurrent::Concern::Logging
end
class Concurrent::ThreadPoolExecutor < Concurrent::RubyThreadPoolExecutor
end
class Concurrent::FixedThreadPool < Concurrent::ThreadPoolExecutor
  def initialize(num_threads, opts = nil); end
end
class Concurrent::CachedThreadPool < Concurrent::ThreadPoolExecutor
  def initialize(opts = nil); end
  def ns_initialize(opts); end
end
class Concurrent::Utility::ProcessorCounter
  def available_processor_count; end
  def compute_cpu_quota; end
  def compute_cpu_shares; end
  def compute_physical_processor_count; end
  def compute_processor_count; end
  def cpu_quota; end
  def cpu_shares; end
  def initialize; end
  def physical_processor_count; end
  def processor_count; end
  def run(command); end
end
class Concurrent::MutexAtomicBoolean
  def false?; end
  def initialize(initial = nil); end
  def make_false; end
  def make_true; end
  def ns_make_value(value); end
  def synchronize; end
  def true?; end
  def value; end
  def value=(value); end
  extend Concurrent::Synchronization::SafeInitialization
end
class Concurrent::AtomicBoolean < Concurrent::MutexAtomicBoolean
  def inspect; end
  def to_s; end
end
module Concurrent::Utility::NativeInteger
  def ensure_integer(value); end
  def ensure_integer_and_bounds(value); end
  def ensure_lower_bound(value); end
  def ensure_positive(value); end
  def ensure_positive_and_no_zero(value); end
  def ensure_upper_bound(value); end
  extend Concurrent::Utility::NativeInteger
end
class Concurrent::MutexAtomicFixnum
  def compare_and_set(expect, update); end
  def decrement(delta = nil); end
  def down(delta = nil); end
  def increment(delta = nil); end
  def initialize(initial = nil); end
  def ns_set(value); end
  def synchronize; end
  def up(delta = nil); end
  def update; end
  def value; end
  def value=(value); end
  extend Concurrent::Synchronization::SafeInitialization
end
class Concurrent::AtomicFixnum < Concurrent::MutexAtomicFixnum
  def inspect; end
  def to_s; end
end
class Concurrent::CyclicBarrier < Concurrent::Synchronization::LockableObject
  def broken?; end
  def initialize(parties, &block); end
  def ns_generation_done(generation, status, continue = nil); end
  def ns_initialize(parties, &block); end
  def ns_next_generation; end
  def number_waiting; end
  def parties; end
  def reset; end
  def wait(timeout = nil); end
end
class Concurrent::CyclicBarrier::Generation < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
  def status; end
  def status=(_); end
end
class Concurrent::MutexCountDownLatch < Concurrent::Synchronization::LockableObject
  def count; end
  def count_down; end
  def initialize(count = nil); end
  def ns_initialize(count); end
  def wait(timeout = nil); end
end
class Concurrent::CountDownLatch < Concurrent::MutexCountDownLatch
end
class Concurrent::Synchronization::Lock < Concurrent::Synchronization::LockableObject
  def broadcast; end
  def ns_broadcast; end
  def ns_signal; end
  def ns_wait(timeout = nil); end
  def ns_wait_until(timeout = nil, &condition); end
  def signal; end
  def synchronize; end
  def wait(timeout = nil); end
  def wait_until(timeout = nil, &condition); end
end
class Concurrent::ReadWriteLock < Concurrent::Synchronization::Object
  def acquire_read_lock; end
  def acquire_write_lock; end
  def has_waiters?; end
  def initialize; end
  def max_readers?(c = nil); end
  def max_writers?(c = nil); end
  def release_read_lock; end
  def release_write_lock; end
  def running_readers(c = nil); end
  def running_readers?(c = nil); end
  def running_writer?(c = nil); end
  def waiting_writer?(c = nil); end
  def waiting_writers(c = nil); end
  def with_read_lock; end
  def with_write_lock; end
  def write_locked?; end
  extend Concurrent::Synchronization::SafeInitialization
end
class Concurrent::FiberLocalVar
  def bind(value); end
  def default; end
  def initialize(default = nil, &default_block); end
  def value; end
  def value=(value); end
end
class Concurrent::ReentrantReadWriteLock < Concurrent::Synchronization::Object
  def acquire_read_lock; end
  def acquire_write_lock; end
  def initialize; end
  def max_readers?(c = nil); end
  def max_writers?(c = nil); end
  def release_read_lock; end
  def release_write_lock; end
  def running_readers(c = nil); end
  def running_readers?(c = nil); end
  def running_writer?(c = nil); end
  def try_read_lock; end
  def try_write_lock; end
  def waiting_or_running_writer?(c = nil); end
  def waiting_writers(c = nil); end
  def with_read_lock; end
  def with_write_lock; end
  extend Concurrent::Synchronization::SafeInitialization
end
class Concurrent::MutexSemaphore < Concurrent::Synchronization::LockableObject
  def acquire(permits = nil); end
  def available_permits; end
  def drain_permits; end
  def initialize(count); end
  def ns_initialize(count); end
  def reduce_permits(reduction); end
  def release(permits = nil); end
  def try_acquire(permits = nil, timeout = nil); end
  def try_acquire_now(permits); end
  def try_acquire_timed(permits, timeout); end
end
class Concurrent::Semaphore < Concurrent::MutexSemaphore
end
class Concurrent::SimpleExecutorService < Concurrent::RubyExecutorService
  def <<(task); end
  def kill; end
  def ns_initialize(*args); end
  def post(*args, &task); end
  def running?; end
  def self.<<(task); end
  def self.post(*args); end
  def shutdown; end
  def shutdown?; end
  def shuttingdown?; end
  def wait_for_termination(timeout = nil); end
end
class Concurrent::IndirectImmediateExecutor < Concurrent::ImmediateExecutor
  def initialize; end
  def post(*args, &task); end
end
class Concurrent::RubySingleThreadExecutor < Concurrent::RubyThreadPoolExecutor
  def initialize(opts = nil); end
  include Concurrent::SerialExecutorService
end
class Concurrent::SafeTaskExecutor < Concurrent::Synchronization::LockableObject
  def execute(*args); end
  def initialize(task, opts = nil); end
end
class Concurrent::SerializedExecution < Concurrent::Synchronization::LockableObject
  def call_job(job); end
  def initialize; end
  def ns_initialize; end
  def post(executor, *args, &task); end
  def posts(posts); end
  def work(job); end
  include Concurrent::Concern::Logging
end
class Concurrent::SerializedExecution::Job < Struct
  def args; end
  def args=(_); end
  def block; end
  def block=(_); end
  def call; end
  def executor; end
  def executor=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
end
class Concurrent::SerializedExecutionDelegator < SimpleDelegator
  def initialize(executor); end
  def post(*args, &task); end
  include Concurrent::SerialExecutorService
end
class Concurrent::SingleThreadExecutor < Concurrent::RubySingleThreadExecutor
end
class Concurrent::Collection::CopyOnWriteObserverSet < Concurrent::Synchronization::LockableObject
  def add_observer(observer = nil, func = nil, &block); end
  def clear_observers_and_return_old; end
  def count_observers; end
  def delete_observer(observer); end
  def delete_observers; end
  def initialize; end
  def notify_and_delete_observers(*args, &block); end
  def notify_observers(*args, &block); end
  def notify_to(observers, *args); end
  def ns_initialize; end
  def observers; end
  def observers=(new_set); end
end
class Concurrent::Collection::CopyOnNotifyObserverSet < Concurrent::Synchronization::LockableObject
  def add_observer(observer = nil, func = nil, &block); end
  def count_observers; end
  def delete_observer(observer); end
  def delete_observers; end
  def duplicate_and_clear_observers; end
  def duplicate_observers; end
  def initialize; end
  def notify_and_delete_observers(*args, &block); end
  def notify_observers(*args, &block); end
  def notify_to(observers, *args); end
  def ns_initialize; end
end
module Concurrent::Concern::Observable
  def add_observer(observer = nil, func = nil, &block); end
  def count_observers; end
  def delete_observer(observer); end
  def delete_observers; end
  def observers; end
  def observers=(arg0); end
  def with_observer(observer = nil, func = nil, &block); end
end
class Concurrent::IVar < Concurrent::Synchronization::LockableObject
  def add_observer(observer = nil, func = nil, &block); end
  def check_for_block_or_value!(block_given, value); end
  def complete(success, value, reason); end
  def complete_without_notification(success, value, reason); end
  def fail(reason = nil); end
  def initialize(value = nil, opts = nil, &block); end
  def notify_observers(value, reason); end
  def ns_complete_without_notification(success, value, reason); end
  def ns_initialize(value, opts); end
  def safe_execute(task, args = nil); end
  def set(value = nil); end
  def try_set(value = nil, &block); end
  include Concurrent::Concern::Obligation
  include Concurrent::Concern::Observable
end
module Concurrent::Options
  def self.executor(executor_identifier); end
  def self.executor_from_options(opts = nil); end
end
class Concurrent::ScheduledTask < Concurrent::IVar
  def <=>(other); end
  def cancel; end
  def cancelled?; end
  def execute; end
  def executor; end
  def fail(reason = nil); end
  def initial_delay; end
  def initialize(delay, opts = nil, &task); end
  def ns_reschedule(delay); end
  def ns_schedule(delay); end
  def process_task; end
  def processing?; end
  def reschedule(delay); end
  def reset; end
  def schedule_time; end
  def self.execute(delay, opts = nil, &task); end
  def set(value = nil); end
  def try_set(value = nil, &block); end
  include Comparable
end
class Concurrent::Collection::RubyNonConcurrentPriorityQueue
  def <<(item); end
  def clear; end
  def delete(item); end
  def deq; end
  def empty?; end
  def enq(item); end
  def has_priority?(item); end
  def include?(item); end
  def initialize(opts = nil); end
  def length; end
  def ordered?(x, y); end
  def peek; end
  def pop; end
  def push(item); end
  def self.from_list(list, opts = nil); end
  def shift; end
  def sink(k); end
  def size; end
  def swap(x, y); end
  def swim(k); end
end
class Concurrent::Collection::NonConcurrentPriorityQueue < Concurrent::Collection::RubyNonConcurrentPriorityQueue
  def <<(item); end
  def deq; end
  def enq(item); end
  def has_priority?(item); end
  def shift; end
  def size; end
end
class Concurrent::TimerSet < Concurrent::RubyExecutorService
  def <<(task); end
  def initialize(opts = nil); end
  def kill; end
  def ns_initialize(opts); end
  def ns_post_task(task); end
  def ns_reset_if_forked; end
  def ns_shutdown_execution; end
  def post(delay, *args, &task); end
  def post_task(task); end
  def process_tasks; end
  def remove_task(task); end
end
class Concurrent::Synchronization::Condition < Concurrent::Synchronization::LockableObject
  def broadcast; end
  def initialize(lock); end
  def ns_broadcast; end
  def ns_signal; end
  def ns_wait(timeout = nil); end
  def ns_wait_until(timeout = nil, &condition); end
  def self.new(*args, &block); end
  def self.private_new(*args, &block); end
  def signal; end
  def wait(timeout = nil); end
  def wait_until(timeout = nil, &condition); end
end
class Concurrent::AtomicMarkableReference < Concurrent::Synchronization::Object
  def __initialize_atomic_fields__; end
  def compare_and_set(expected_val, new_val, expected_mark, new_mark); end
  def compare_and_set_reference(expected, value); end
  def compare_and_swap(expected_val, new_val, expected_mark, new_mark); end
  def get; end
  def immutable_array(*args); end
  def initialize(value = nil, mark = nil); end
  def mark; end
  def marked?; end
  def reference; end
  def reference=(value); end
  def set(new_val, new_mark); end
  def swap_reference(value); end
  def try_update!; end
  def try_update; end
  def update; end
  def update_reference(&block); end
  def value; end
  extend Concurrent::Synchronization::SafeInitialization
end
class Concurrent::Agent < Concurrent::Synchronization::LockableObject
  def <<(action); end
  def await; end
  def await_for!(timeout); end
  def await_for(timeout); end
  def deref; end
  def enqueue_action_job(action, args, executor); end
  def enqueue_await_job(latch); end
  def error; end
  def error_mode; end
  def execute_next_job; end
  def failed?; end
  def handle_error(error); end
  def initialize(initial, opts = nil); end
  def ns_enqueue_job(job, index = nil); end
  def ns_find_last_job_for_thread; end
  def ns_initialize(initial, opts); end
  def ns_post_next_job; end
  def ns_validate(value); end
  def post(*args, &action); end
  def reason; end
  def restart(new_value, opts = nil); end
  def self.await(*agents); end
  def self.await_for!(timeout, *agents); end
  def self.await_for(timeout, *agents); end
  def send!(*args, &action); end
  def send(*args, &action); end
  def send_off!(*args, &action); end
  def send_off(*args, &action); end
  def send_via!(executor, *args, &action); end
  def send_via(executor, *args, &action); end
  def stopped?; end
  def value; end
  def wait(timeout = nil); end
  include Concurrent::Concern::Observable
end
class Concurrent::Agent::Job < Struct
  def action; end
  def action=(_); end
  def args; end
  def args=(_); end
  def caller; end
  def caller=(_); end
  def executor; end
  def executor=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
end
class Concurrent::Agent::Error < StandardError
  def initialize(message = nil); end
end
class Concurrent::Agent::ValidationError < Concurrent::Agent::Error
  def initialize(message = nil); end
end
class Concurrent::Atom < Concurrent::Synchronization::Object
  def __initialize_atomic_fields__; end
  def compare_and_set(old_value, new_value); end
  def compare_and_set_value(expected, value); end
  def deref; end
  def initialize(value, opts = nil); end
  def reset(new_value); end
  def swap(*args); end
  def swap_value(value); end
  def update_value(&block); end
  def valid?(new_value); end
  def value; end
  def value=(value); end
  extend Concurrent::Synchronization::SafeInitialization
  include Concurrent::Concern::Observable
end
class Concurrent::Array < Array
end
class Set
end
module Set::SubclassCompatible
