---
AppContact:
  id:
    ImplicitOrderingChecker:
      enabled: false
AppContactCategory:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  app_contacts:
    ForeignKeyCascadeChecker:
      enabled: false
AppContactEmail:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AppContactStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  app_contacts:
    ForeignKeyCascadeChecker:
      enabled: false
AppContactTelephone:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AppContactTopic:
  id:
    ImplicitOrderingChecker:
      enabled: false
AppDocument:
  id:
    ImplicitOrderingChecker:
      enabled: false
AppDocumentAudit:
  id:
    ImplicitOrderingChecker:
      enabled: false
AppDocumentAuditEvent:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
AppDocumentAuditLevel:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
AppDocumentCategory:
  id:
    ImplicitOrderingChecker:
      enabled: false
AppDocumentCategoryMaster:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AppDocumentStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AppDocumentTag:
  id:
    ImplicitOrderingChecker:
      enabled: false
AppDocumentTagMaster:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AppDocumentVersion:
  id:
    ImplicitOrderingChecker:
      enabled: false
AppTimeline:
  id:
    ImplicitOrderingChecker:
      enabled: false
AppTimelineAudit:
  id:
    ImplicitOrderingChecker:
      enabled: false
AppTimelineAuditEvent:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
AppTimelineAuditLevel:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
AppTimelineCategory:
  id:
    ImplicitOrderingChecker:
      enabled: false
AppTimelineCategoryMaster:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AppTimelineStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AppTimelineTag:
  id:
    ImplicitOrderingChecker:
      enabled: false
AppTimelineTagMaster:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AdminIdentityStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AreaOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
AreaOccurrenceStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
Avatar:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AvatarAssignment:
  id:
    ImplicitOrderingChecker:
      enabled: false
AvatarCapability:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AvatarMembership:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AvatarMembershipStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AvatarMoniker:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AvatarMonikerStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AvatarOwnershipPeriod:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AvatarOwnershipStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AvatarPermission:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AvatarRole:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
AvatarRolePermission:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
Billing::StripeEvent:
  id:
    ImplicitOrderingChecker:
      enabled: false
ComContact:
  id:
    ImplicitOrderingChecker:
      enabled: false
ComContactCategory:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  com_contacts:
    ForeignKeyCascadeChecker:
      enabled: false
ComContactEmail:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
ComContactStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
ComContactTelephone:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
ComContactTopic:
  id:
    ImplicitOrderingChecker:
      enabled: false
ComDocument:
  id:
    ImplicitOrderingChecker:
      enabled: false
ComDocumentAudit:
  id:
    ImplicitOrderingChecker:
      enabled: false
ComDocumentAuditEvent:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
ComDocumentAuditLevel:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
ComDocumentCategory:
  id:
    ImplicitOrderingChecker:
      enabled: false
ComDocumentCategoryMaster:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
ComDocumentStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
ComDocumentTag:
  id:
    ImplicitOrderingChecker:
      enabled: false
ComDocumentTagMaster:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
ComDocumentVersion:
  id:
    ImplicitOrderingChecker:
      enabled: false
ComTimeline:
  id:
    ImplicitOrderingChecker:
      enabled: false
ComTimelineAudit:
  id:
    ImplicitOrderingChecker:
      enabled: false
ComTimelineAuditEvent:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
ComTimelineAuditLevel:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
ComTimelineCategory:
  id:
    ImplicitOrderingChecker:
      enabled: false
ComTimelineCategoryMaster:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
ComTimelineStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
ComTimelineTag:
  id:
    ImplicitOrderingChecker:
      enabled: false
ComTimelineTagMaster:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
ClientIdentityStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
Client:
  id:
    ImplicitOrderingChecker:
      enabled: false
  avatars:
    ForeignKeyCascadeChecker:
      enabled: false
DomainOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
DomainOccurrenceStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
DepartmentStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
DivisionStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
EmailOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
EmailOccurrenceStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
Handle:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
HandleAssignment:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
HandleAssignmentStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
HandleStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
IpOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
IpOccurrenceStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
OrgContact:
  id:
    ImplicitOrderingChecker:
      enabled: false
OrgContactCategory:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  org_contacts:
    ForeignKeyCascadeChecker:
      enabled: false
OrgContactEmail:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
OrgContactStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
OrgContactTelephone:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
OrgContactTopic:
  id:
    ImplicitOrderingChecker:
      enabled: false
OrganizationStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
OrgDocument:
  id:
    ImplicitOrderingChecker:
      enabled: false
OrgDocumentAudit:
  id:
    ImplicitOrderingChecker:
      enabled: false
OrgDocumentAuditEvent:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
OrgDocumentAuditLevel:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
OrgDocumentCategory:
  id:
    ImplicitOrderingChecker:
      enabled: false
OrgDocumentCategoryMaster:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
OrgDocumentStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
OrgDocumentTag:
  id:
    ImplicitOrderingChecker:
      enabled: false
OrgDocumentTagMaster:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
OrgDocumentVersion:
  id:
    ImplicitOrderingChecker:
      enabled: false
OrgTimeline:
  id:
    ImplicitOrderingChecker:
      enabled: false
OrgTimelineAudit:
  id:
    ImplicitOrderingChecker:
      enabled: false
OrgTimelineAuditEvent:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
OrgTimelineAuditLevel:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
OrgTimelineCategory:
  id:
    ImplicitOrderingChecker:
      enabled: false
OrgTimelineCategoryMaster:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
OrgTimelineStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
OrgTimelineTag:
  id:
    ImplicitOrderingChecker:
      enabled: false
OrgTimelineTagMaster:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
Post:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  post_versions:
    ForeignKeyCascadeChecker:
      enabled: false
PostReview:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
PostReviewStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
PostStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
Staff:
  id:
    ImplicitOrderingChecker:
      enabled: false
StaffIdentityAudit:
  id:
    ImplicitOrderingChecker:
      enabled: false
StaffIdentityAuditEvent:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
StaffIdentityAuditLevel:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
StaffIdentityEmail:
  id:
    ImplicitOrderingChecker:
      enabled: false
  lower(address):
    MissingUniqueIndexChecker:
      enabled: false
StaffIdentityEmailStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
StaffIdentityPasskey:
  id:
    ImplicitOrderingChecker:
      enabled: false
StaffIdentityPasskeyStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
StaffIdentitySecret:
  id:
    ImplicitOrderingChecker:
      enabled: false
StaffIdentitySecretStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
StaffIdentityStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
StaffIdentityTelephone:
  id:
    ImplicitOrderingChecker:
      enabled: false
  lower(number):
    MissingUniqueIndexChecker:
      enabled: false
StaffIdentityTelephoneStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
StaffMessage:
  id:
    ImplicitOrderingChecker:
      enabled: false
  admin_messages:
    ForeignKeyCascadeChecker:
      enabled: false
StaffNotification:
  id:
    ImplicitOrderingChecker:
      enabled: false
  admin_notifications:
    ForeignKeyCascadeChecker:
      enabled: false
StaffOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
StaffOccurrenceStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
StaffTokenStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
TelephoneOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
TelephoneOccurrenceStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
UserIdentityAudit:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserIdentityAuditEvent:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
UserIdentityAuditLevel:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
UserIdentityEmail:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserIdentityEmailStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
UserIdentityOneTimePassword:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserIdentityOneTimePasswordStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
UserIdentityPasskey:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserIdentityPasskeyStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
UserIdentitySecret:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserIdentitySecretStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
UserIdentitySocialApple:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserIdentitySocialAppleStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
UserIdentitySocialGoogle:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserIdentitySocialGoogleStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
UserIdentityStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
UserIdentityTelephone:
  id:
    ImplicitOrderingChecker:
      enabled: false
  lower(number):
    MissingUniqueIndexChecker:
      enabled: false
UserIdentityTelephoneStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
UserMembership:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserMessage:
  id:
    ImplicitOrderingChecker:
      enabled: false
  client_messages:
    ForeignKeyCascadeChecker:
      enabled: false
UserNotification:
  id:
    ImplicitOrderingChecker:
      enabled: false
  client_notifications:
    ForeignKeyCascadeChecker:
      enabled: false
User:
  id:
    ImplicitOrderingChecker:
      enabled: false
  owned_clients:
    ForeignKeyCascadeChecker:
      enabled: false
UserOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserOccurrenceStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
UserTokenStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
UserWorkspace:
  id:
    ImplicitOrderingChecker:
      enabled: false
Workspace:
  id:
    ImplicitOrderingChecker:
      enabled: false
WorkspaceStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
  lower(id):
    MissingUniqueIndexChecker:
      enabled: false
ZipOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
ZipOccurrenceStatus:
  id:
    PrimaryKeyTypeChecker:
      enabled: false
Admin:
  id:
    ImplicitOrderingChecker:
      enabled: false
AdminMessage:
  id:
    ImplicitOrderingChecker:
      enabled: false
AdminNotification:
  id:
    ImplicitOrderingChecker:
      enabled: false
AppTimelineVersion:
  id:
    ImplicitOrderingChecker:
      enabled: false
AreaDomainOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
AreaEmailOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
AreaIpOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
AreaStaffOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
AreaTelephoneOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
AreaUserOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
AreaZipOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
AvatarBlock:
  id:
    ImplicitOrderingChecker:
      enabled: false
AvatarFollow:
  id:
    ImplicitOrderingChecker:
      enabled: false
AvatarMute:
  id:
    ImplicitOrderingChecker:
      enabled: false
ClientAvatarAccess:
  id:
    ImplicitOrderingChecker:
      enabled: false
ClientAvatarDeletion:
  id:
    ImplicitOrderingChecker:
      enabled: false
ClientAvatarExtraction:
  id:
    ImplicitOrderingChecker:
      enabled: false
ClientAvatarImpersonation:
  id:
    ImplicitOrderingChecker:
      enabled: false
ClientAvatarOversight:
  id:
    ImplicitOrderingChecker:
      enabled: false
ClientAvatarSuspension:
  id:
    ImplicitOrderingChecker:
      enabled: false
ClientAvatarVisibility:
  id:
    ImplicitOrderingChecker:
      enabled: false
ClientMessage:
  id:
    ImplicitOrderingChecker:
      enabled: false
ClientNotification:
  id:
    ImplicitOrderingChecker:
      enabled: false
ComTimelineVersion:
  id:
    ImplicitOrderingChecker:
      enabled: false
Department:
  id:
    ImplicitOrderingChecker:
      enabled: false
Division:
  id:
    ImplicitOrderingChecker:
      enabled: false
DomainEmailOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
DomainIpOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
DomainStaffOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
DomainTelephoneOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
DomainUserOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
DomainZipOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
EmailIpOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
EmailStaffOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
EmailTelephoneOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
EmailUserOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
EmailZipOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
IpStaffOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
IpTelephoneOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
IpUserOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
IpZipOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
OrgTimelineVersion:
  id:
    ImplicitOrderingChecker:
      enabled: false
Organization:
  id:
    ImplicitOrderingChecker:
      enabled: false
PostVersion:
  id:
    ImplicitOrderingChecker:
      enabled: false
StaffAdmin:
  id:
    ImplicitOrderingChecker:
      enabled: false
StaffTelephoneOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
StaffToken:
  id:
    ImplicitOrderingChecker:
      enabled: false
StaffUserOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
StaffZipOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
TelephoneUserOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
TelephoneZipOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserClient:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserClientDeletion:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserClientDiscovery:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserClientImpersonation:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserClientObservation:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserClientRevocation:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserClientSuspension:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserToken:
  id:
    ImplicitOrderingChecker:
      enabled: false
UserZipOccurrence:
  id:
    ImplicitOrderingChecker:
      enabled: false
