# Ignore false positives from Rails' ActionText and ActiveStorage
ActionText::RichText:
  enabled: false
ActiveStorage::Attachment:
  enabled: false
ActiveStorage::Blob:
  enabled: false
ActiveStorage::VariantRecord:
  enabled: false
  enabled: false

UserIdentityEmail:
  ColumnPresenceChecker:
    address:
      enabled: false
    MissingUniqueIndexChecker:
      address:
        enabled: false

StaffIdentityEmail:
  ColumnPresenceChecker:
    address:
      enabled: false
  MissingUniqueIndexChecker:
    address:
      enabled: false

UserIdentityTelephone:
  MissingUniqueIndexChecker:
    number:
      enabled: false

StaffIdentityTelephone:
  MissingUniqueIndexChecker:
    number:
      enabled: false
