# ============================================================
# RuboCop Configuration
# ============================================================
# このファイルはRubyコードの静的解析とフォーマットを設定します
#
# 設定カテゴリ:
# 1. 基本設定（AllCops, Plugins, Inheritance）
# 2. レイアウト・フォーマット（Layout, Style）
# 3. コード品質（Metrics, Lint）
# 4. セキュリティ（Security）
# 5. フレームワーク固有（Rails）
# 6. パフォーマンス（Performance）
# 7. テスト（Minitest）
# 8. その他（Rake, I18n, Naming）

# ============================================================
# 1. 基本設定
# ============================================================

# Omakase Ruby styling for Railsを継承
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# プラグイン
plugins:
  - rubocop-i18n
  - rubocop-rake
  - rubocop-rubycw
  - rubocop-minitest
  - rubocop-performance
  - rubocop-thread_safety

# 全Copに適用される設定
AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  UseCache: true
  CacheRootDirectory: tmp/rubocop_cache
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'db/*_schema.rb'
    - 'bin/**/*'
    - 'tmp/**/*'
  Include:
    - '**/*.rb'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'

# ============================================================
# 2. レイアウト・フォーマット
# ============================================================

Layout:
  Enabled: true

# ---------- インデント ----------
Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

Layout/IndentationStyle:
  Enabled: true
  EnforcedStyle: spaces

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

# ---------- 空行 ----------
Layout/EmptyLinesAroundBlockBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

# メソッド間の空行を強制（1行の空行を要求）
Layout/EmptyLineBetweenDefs:
  Enabled: true
  AllowAdjacentOneLineDefs: false
  NumberOfEmptyLines: 1

# 複数の連続空行を禁止
Layout/EmptyLines:
  Enabled: true

# ---------- スペース ----------
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space

Layout/SpaceInsideParens:
  Enabled: true
  EnforcedStyle: no_space

Layout/SpaceInsideRangeLiteral:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterSemicolon:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

# ---------- 末尾の空白・空行 ----------
Layout/TrailingWhitespace:
  Enabled: true
  AllowInHeredoc: false

Layout/TrailingEmptyLines:
  Enabled: true
  EnforcedStyle: final_newline

# ---------- 行の長さ ----------
Layout/LineLength:
  Max: 160
  Exclude:
    - 'config/**/*'
    - 'db/**/*_migrate/**/*'

# ---------- 複数行のフォーマット ----------
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_first_argument

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_first_parameter

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

# ---------- コメント ----------
Layout/CommentIndentation:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: true

# ============================================================
# Style（コーディングスタイル）
# ============================================================

# ---------- 文字列 ----------
Style/AsciiComments:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false  # 大規模な変更が必要なため無効化

# ---------- ハッシュ・配列 ----------
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: either

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  Enabled: true
  EnforcedStyle: percent
  MinSize: 3

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: percent
  MinSize: 3

# ---------- メソッド定義 ----------
Style/DefWithParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses

Style/EmptyMethod:
  Enabled: true
  EnforcedStyle: expanded

# ---------- 条件式 ----------
Style/ConditionalAssignment:
  Enabled: true
  EnforcedStyle: assign_to_condition

Style/TernaryParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses_when_complex

# ---------- 数値・リテラル ----------
Style/NumericLiterals:
  Enabled: true
  MinDigits: 5
  Strict: false

Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    "%": "()"
    "%i": "()"
    "%I": "()"
    "%q": "()"
    "%Q": "()"
    "%r": "{}"
    "%s": "()"
    "%w": "()"
    "%W": "()"
    "%x": "()"

# ---------- その他のStyle ----------
Style/Documentation:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/HashConversion:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/MultilineInPatternThen:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/NumberedParameters:
  Enabled: true

Style/NumberedParametersLimit:
  Enabled: true

Style/QuotedSymbols:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/SelectByRegexp:
  Enabled: true

Style/StringChars:
  Enabled: true

Style/SwapValues:
  Enabled: true

# ============================================================
# 3. コード品質
# ============================================================

# ---------- Metrics（コード複雑度・サイズ制限） ----------
Metrics/AbcSize:
  Max: 18
  Exclude:
    - 'db/**/*_migrate/**/*'
    - 'test/**/*'

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'config/**/*'
    - 'db/**/*_migrate/**/*'
    - 'test/**/*'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 12
  Exclude:
    - 'db/**/*_migrate/**/*'
    - 'test/**/*'

Metrics/ModuleLength:
  Max: 150

Metrics/ParameterLists:
  Max: 5
  MaxOptionalParameters: 3

Metrics/PerceivedComplexity:
  Max: 8

# ---------- Lint（潜在的なバグの検出） ----------
Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousOperatorPrecedence:
  Enabled: true

Lint/AmbiguousRange:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true
  AllowComments: true
  AllowEmptyLambdas: true
  Exclude:
    - 'test/**/*'

Lint/EmptyClass:
  Enabled: true
  AllowComments: true
  Exclude:
    - 'app/services/**/*'
    - 'test/**/*'

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/RequireRelativeSelfPath:
  Enabled: true

Lint/SymbolConversion:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UselessRuby2Keywords:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true
  Exclude:
    - 'config/initializers/**/*'

# ============================================================
# 4. セキュリティ
# ============================================================

Security:
  Enabled: true

# ---------- 危険なコード実行 ----------
Security/Eval:
  Enabled: true

Security/JSONLoad:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Security/YAMLLoad:
  Enabled: true

Security/Open:
  Enabled: true

Security/CompoundHash:
  Enabled: true

Security/IoMethods:
  Enabled: true

# ---------- デバッグコード検出 ----------
Lint/Debugger:
  Enabled: true

# ---------- 未使用引数検出 ----------
Lint/UnusedMethodArgument:
  Enabled: true
  AllowUnusedKeywordArguments: false
  IgnoreEmptyMethods: true
  Exclude:
    - 'test/**/*'

Lint/UnusedBlockArgument:
  Enabled: true
  AllowUnusedKeywordArguments: false
  IgnoreEmptyBlocks: true
  Exclude:
    - 'test/**/*'

# ---------- 非推奨API検出 ----------
Lint/UriEscapeUnescape:
  Enabled: true

# ============================================================
# 5. Rails固有の設定
# ============================================================

Rails:
  Enabled: true

# ---------- セキュリティ関連 ----------
Rails/OutputSafety:
  Enabled: true

Rails/BulkChangeTable:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true
  AllowedMethods:
    - touch

Rails/UnknownEnv:
  Enabled: true

Rails/FilePath:
  Enabled: true

# ---------- Rails Cops（自動有効化された新しいCop） ----------
Rails/ActionControllerFlashBeforeRender:
  Enabled: true

Rails/ActionControllerTestCase:
  Enabled: true

Rails/ActionOrder:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/ActiveSupportOnLoad:
  Enabled: true

Rails/AddColumnIndex:
  Enabled: true

Rails/AfterCommitOverride:
  Enabled: true

Rails/AttributeDefaultBlockValue:
  Enabled: true

Rails/CompactBlank:
  Enabled: true

Rails/DangerousColumnNames:
  Enabled: true

Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: true

Rails/DotSeparatedKeys:
  Enabled: true

Rails/DuplicateAssociation:
  Enabled: true

Rails/DuplicateScope:
  Enabled: true

Rails/DurationArithmetic:
  Enabled: true

Rails/EagerEvaluationLogMessage:
  Enabled: true

Rails/EnumSyntax:
  Enabled: true

Rails/EnvLocal:
  Enabled: true

Rails/ExpandedDateRange:
  Enabled: true

Rails/FindById:
  Enabled: true

Rails/FindEach:
  Enabled: true

Rails/FreezeTime:
  Enabled: true

Rails/I18nLazyLookup:
  Enabled: true

Rails/I18nLocaleAssignment:
  Enabled: true

Rails/I18nLocaleTexts:
  Enabled: true

Rails/IgnoredColumnsAssignment:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/MigrationClassName:
  Enabled: true

Rails/MultipleRoutePaths:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RedundantActiveRecordAllMethod:
  Enabled: true

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: true

Rails/RedundantTravelBack:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ResponseParsedBody:
  Enabled: true

Rails/RootJoinChain:
  Enabled: true

Rails/RootPathnameMethods:
  Enabled: true

Rails/RootPublicPath:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/StripHeredoc:
  Enabled: true

Rails/StrongParametersExpect:
  Enabled: true

Rails/ThreeStateBooleanColumn:
  Enabled: true

Rails/TimeZoneAssignment:
  Enabled: true

Rails/ToFormattedS:
  Enabled: true

Rails/ToSWithArgument:
  Enabled: true

Rails/TopLevelHashWithIndifferentAccess:
  Enabled: true

Rails/TransactionExitStatement:
  Enabled: true

Rails/UnusedRenderContent:
  Enabled: true

Rails/WhereEquals:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/WhereMissing:
  Enabled: true

Rails/WhereNot:
  Enabled: true

Rails/WhereNotWithMultipleConditions:
  Enabled: true

Rails/WhereRange:
  Enabled: true

Rails/FindByOrAssignmentMemoization:
  Enabled: true

Rails/OrderArguments:
  Enabled: true

# ============================================================
# 6. パフォーマンス
# ============================================================

Performance:
  Enabled: true

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/BlockGivenWithExplicitBlock:
  Enabled: true

Performance/CollectionLiteralInLoop:
  Enabled: true

Performance/ConcurrentMonotonicTime:
  Enabled: true

Performance/ConstantRegexp:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/MapCompact:
  Enabled: true

Performance/MethodObjectAsBlock:
  Enabled: true

Performance/RedundantEqualityComparisonBlock:
  Enabled: true

Performance/RedundantSplitRegexpArgument:
  Enabled: true

Performance/StringIdentifierArgument:
  Enabled: true

Performance/Sum:
  Enabled: true

# ============================================================
# 7. テスト（Minitest）
# ============================================================

Minitest:
  Enabled: true

# ---------- アサーション ----------
Minitest/AssertEmpty:
  Enabled: true

Minitest/AssertEqual:
  Enabled: true

Minitest/AssertIncludes:
  Enabled: true

Minitest/AssertInstanceOf:
  Enabled: true

Minitest/AssertKindOf:
  Enabled: true

Minitest/AssertMatch:
  Enabled: true

Minitest/AssertNil:
  Enabled: true

Minitest/AssertOperator:
  Enabled: true

Minitest/AssertPathExists:
  Enabled: true

Minitest/AssertPredicate:
  Enabled: true

Minitest/AssertRespondTo:
  Enabled: true

Minitest/AssertSame:
  Enabled: true

Minitest/AssertTruthy:
  Enabled: true

Minitest/AssertWithExpectedArgument:
  Enabled: true

# ---------- Refuteアサーション ----------
Minitest/RefuteEmpty:
  Enabled: true

Minitest/RefuteEqual:
  Enabled: true

Minitest/RefuteFalse:
  Enabled: true

Minitest/RefuteIncludes:
  Enabled: true

Minitest/RefuteInstanceOf:
  Enabled: true

Minitest/RefuteKindOf:
  Enabled: true

Minitest/RefuteMatch:
  Enabled: true

Minitest/RefuteNil:
  Enabled: true

Minitest/RefuteOperator:
  Enabled: true

Minitest/RefutePathExists:
  Enabled: true

Minitest/RefutePredicate:
  Enabled: true

Minitest/RefuteRespondTo:
  Enabled: true

Minitest/RefuteSame:
  Enabled: true

# ---------- テスト品質 ----------
Minitest/AssertionInLifecycleHook:
  Enabled: true

Minitest/DuplicateTestRun:
  Enabled: true

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Minitest/Focus:
  Enabled: true

Minitest/GlobalExpectations:
  Enabled: false

Minitest/LifecycleHooksOrder:
  Enabled: true

Minitest/LiteralAsActualArgument:
  Enabled: true

Minitest/MultipleAssertions:
  Enabled: true
  Max: 8

Minitest/NoAssertions:
  Enabled: false

Minitest/NoTestCases:
  Enabled: false

Minitest/NonExecutableTestMethod:
  Enabled: true

Minitest/NonPublicTestMethod:
  Enabled: true

Minitest/RedundantMessageArgument:
  Enabled: true

Minitest/ReturnInTestMethod:
  Enabled: true

Minitest/SkipEnsure:
  Enabled: true

Minitest/SkipWithoutReason:
  Enabled: false

Minitest/TestFileName:
  Enabled: true

Minitest/TestMethodName:
  Enabled: true

Minitest/UnreachableAssertion:
  Enabled: true

Minitest/UnspecifiedException:
  Enabled: true

Minitest/UselessAssertion:
  Enabled: true

# ============================================================
# 8. その他
# ============================================================

# ---------- Naming（命名規則） ----------
Naming/BlockForwarding:
  Enabled: true

Naming/InclusiveLanguage:
  Enabled: true
  FlaggedTerms:
    whitelist:
      Suggestions:
        - allowlist
        - permitted
    blacklist:
      Suggestions:
        - denylist
        - blocked

# ---------- Rake ----------
Rake:
  Enabled: true

Rake/ClassDefinitionInTask:
  Enabled: true

Rake/Desc:
  Enabled: true

Rake/DuplicateNamespace:
  Enabled: true

Rake/DuplicateTask:
  Enabled: true

Rake/MethodDefinitionInTask:
  Enabled: true

# ---------- I18n ----------
I18n/RailsI18n:
  Enabled: true

I18n/GetText:
  Enabled: false
