# frozen_string_literal: true

# PostgreSQL 18+ uuidv7() migration for string-typed UUID primary keys
# Sets DEFAULT uuidv7()::text for tables that store UUIDs as strings
class SetUuidv7DefaultForStringIdTables < ActiveRecord::Migration[8.2]
  # Tables with string primary keys that store UUIDs (previously generated by Rails via UuidV7PrimaryKey concern)
  STRING_UUID_TABLES = %w(
    avatars
    handles
    posts
    avatar_monikers
    avatar_memberships
    avatar_capabilities
    avatar_ownership_periods
    handle_assignments
    post_reviews
  ).freeze

  def up
    STRING_UUID_TABLES.each do |table_name|
      safety_assured do
        execute(<<~SQL.squish)
          ALTER TABLE #{table_name}
          ALTER COLUMN id SET DEFAULT uuidv7()::text;
        SQL
      end
    end
  end

  def down
    STRING_UUID_TABLES.each do |table_name|
      safety_assured do
        execute(<<~SQL.squish)
          ALTER TABLE #{table_name}
          ALTER COLUMN id DROP DEFAULT;
        SQL
      end
    end
  end
end
