services:
  core:
    container_name: jit-devcontainer-core
    userns_mode: keep-id
    environment:
      - DEVCONTAINER=1
      - RUBY_DEBUG_OPEN=false
  primary:
    container_name: jit-devcontainer-primary
    ports: []
  replica:
    container_name: jit-devcontainer-replica
    ports: []
  valkey:
    container_name: jit-devcontainer-valkey
    ports: []
  master:
    container_name: jit-devcontainer-seaweedfs-master
    ports: []
  volume:
    container_name: jit-devcontainer-seaweedfs-volume
    ports: []
  filer:
    container_name: jit-devcontainer-seaweedfs-filer
    ports: []
  s3:
    container_name: jit-devcontainer-seaweedfs-s3
    ports: []
  loki:
    container_name: jit-devcontainer-loki
    ports: []
  tempo:
    container_name: jit-devcontainer-tempo
    ports: []
  grafana:
    container_name: jit-devcontainer-grafana
    ports: []
