development:
  encrypt: true
  store_options:
    max_age: <%= 1.week.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

test:
  encrypt: true
  store_options:
    max_age: <%= 1.hour.to_i %>
    max_size: <%= 16.megabytes %>
    namespace: <%= Rails.env %>

production:
  encrypt: true
  store_options:
    max_age: <%= 1.week.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>
