# typed: false
# frozen_string_literal: true

require "active_support/core_ext/integer/time"
require Rails.root.join("lib/development_safety_guard")
require Rails.root.join("lib/mailer_url_options_guard")
require Rails.root.join("lib/strict_environment_config")

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails org:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-org.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  config.cache_store = :null_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  # config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = true

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  ## Letter Opener => https://github.com/ryanb/letter_opener
  #  config.action_mailer.delivery_method = :letter_opener
  # config.action_mailer.perform_deliveries = true

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Include source location in query log tags for easier debugging
  config.active_record.query_log_tags = %i(application controller action job source_location)

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  StrictEnvironmentConfig.apply!(config)

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  config.generators.apply_rubocop_autocorrect_after_generate!

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  config.action_dispatch.verbose_redirect_logs = true

  # added by user
  ## for docker
  # config.web_console.permitted_networks = "127.0.0.1", "::1", "172.19.0.0/16"

  # Keep development on local hosts by default. Public-like hosts require an explicit opt-in.
  allowed_hosts = DevelopmentSafetyGuard.allowed_hosts
  config.hosts.concat(allowed_hosts)
  config.host_authorization = { exclude: ->(request) { request.path.start_with?("/health", "/up") } }

  ## file watcher
  config.file_watcher = ActiveSupport::EventedFileUpdateChecker

  # static file serve
  config.public_file_server.enabled = false

  ## Email Settings
  ### Set localhost to be used by links generated in mailer templates.
  config.action_mailer.delivery_method = DevelopmentSafetyGuard.mailer_delivery_method
  config.action_mailer.perform_deliveries = DevelopmentSafetyGuard.perform_deliveries?
  config.action_mailer.default_url_options = { host: "localhost", port: 3001 }
  MailerUrlOptionsGuard.validate!(
    default_url_options: config.action_mailer.default_url_options,
    allowed_hosts: allowed_hosts,
  )
  if DevelopmentSafetyGuard.allow_development_smtp?
    config.action_mailer.smtp_settings = {
      address: "email-smtp.#{ENV.fetch("AWS_SES_REGION", "ap-northeast-1")}.amazonaws.com",
      user_name: Rails.app.creds.option(:AWS_SES_SMTP_USER_NAME),
      password: Rails.app.creds.option(:AWS_SES_SMTP_PASSWORD),
      port: 465,
      tls: true,
      authentication: :login,
    }
  end

  # SMS Provider Configuration - Use test provider in development
  config.sms_provider = ENV.fetch("SMS_PROVIDER", "test")
  DevelopmentSafetyGuard.validate_sms_provider!(sms_provider: config.sms_provider)

  # Enable Gzip compression
  config.middleware.use(Rack::Deflater)

  # Live reload: rack-livereload injects the livereload script tag into HTML responses.
  # Works alongside rails_live_reload which handles file-change detection and WebSocket notifications.
  config.middleware.insert_after(Rack::Deflater, Rack::LiveReload)
end
