# frozen_string_literal: true

require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails org:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-org.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :redis_cache_store, { url: File.exist?("/.dockerenv") ? ENV["REDIS_CACHE_URL"] : "localhost", expires_in: 1.hour, driver: :hiredis }

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = true

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  ## Letter Opener => https://github.com/ryanb/letter_opener
  #  config.action_mailer.delivery_method = :letter_opener
  # config.action_mailer.perform_deliveries = true

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  config.generators.apply_rubocop_autocorrect_after_generate!

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # session
  config.session_store :cookie_store

  # added
  ## to avoid errors
  config.hosts << "localhost"
  config.hosts << "com.www.localdomain"
  config.hosts << "app.www.localdomain"
  config.hosts << "org.www.localdomain"
  config.hosts << "com.api.localdomain"
  config.hosts << "app.api.localdomain"
  config.hosts << "org.api.localdomain"
  config.hosts << "com.news.localdomain"
  config.hosts << "app.news.localdomain"
  config.hosts << "org.news.localdomain"
  config.hosts << "com.docs.localdomain"
  config.hosts << "app.docs.localdomain"
  config.hosts << "org.docs.localdomain"

  # Bullet, a gem to help you avoid N+1 queries and unused eager loading.
  config.after_initialize do
    Bullet.enable        = true
    Bullet.alert         = true
    Bullet.bullet_logger = true
    Bullet.console       = true
    Bullet.rails_logger  = true
    Bullet.add_footer    = true
  end

  ## file watcher
  config.file_watcher = ActiveSupport::EventedFileUpdateChecker

  # Rack Attack preferences
  Rack::Attack.cache.store = Rails.cache

  ## Email Settings
  ### Set localhost to be used by links generated in mailer templates.
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.default_url_options = { host: "localhost", port: 3333 }
  config.action_mailer.smtp_settings = {
    address: ENV["RESEND_SMTP_ENDPOINT"],
    user_name: ENV["RESEND_SMTP_USER_NAME"],
    password: ENV["RESEND_SMTP_PASSWORD"],
    port: 465,
    tls: true
  }

  ## Active Record Encryption
  config.active_record.encryption.primary_key = ENV["ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY"]
  config.active_record.encryption.deterministic_key = ENV["ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY"]
  config.active_record.encryption.key_derivation_salt = ENV["ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT"]
end
