name: CD
on:
  push:
    branches:
      - main
      - develop
  schedule:
    - cron: '0 1 * * 2' # Schedule to run every Tuesday at 10:00 PM JST.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      ECR_REPOSITORY: 841162677945.dkr.ecr.ap-northeast-1.amazonaws.com/umaxica/jit
      AWS_REGION: ap-northeast-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: false
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.7
      - name: Set up Bun
        run: bun install
      - name: bundle install
        run: bundle config set without 'test development' && bundle install
      - name: compile assets pipeline
        run: SECRET_KEY_BASE_DUMMY=1 RAILS_ENV=production bin/rails assets:precompile
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY
      - name: Build production Docker image
        run: |
          docker build --target production \
            -t docker.io/my-organization/my-app:${{ github.sha }} \
            --build-arg COMMIT_HASH=${{ github.sha }} .
#      - name: Run Trivy vulnerability scanner
#        uses: aquasecurity/trivy-action@0.28.0
#        with:
#         image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
#         format: 'table'
#         exit-code: '1'
#         ignore-unfixed: true
#         vuln-type: 'os,library'
#         severity: 'CRITICAL,HIGH'
      - name: Tag and push to Amazon ECR
        run: |
          docker tag docker.io/my-organization/my-app:${{ github.sha }} $ECR_REPOSITORY:latest
          docker tag docker.io/my-organization/my-app:${{ github.sha }} $ECR_REPOSITORY:${{ github.sha }}
          docker push $ECR_REPOSITORY:latest
          docker push $ECR_REPOSITORY:${{ github.sha }}
      - uses: actions/setup-node@v4
        with:
          node-version: '23.x'
      - run: npm init -y
      - name: Build & Deploy Worker
        run: |
          cd ./public
          find . -type f -not -path "*/\.*" -not -name ".*" | while read -r file; do
            relative_path="${file:2}"
            CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }} CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} npx wrangler@latest r2 object put "umaxica-production-cloudflare-r2-asset-jp/$relative_path" --file="$file" --remote
          done