name: Hello
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: ???
jobs:
  hello:
    name: 'First Action!'
    runs-on: ubuntu-latest
    steps:
      - run: |
          date
          ls
          pwd
          echo "hello, world! ${{inputs.greeting}}"
      - uses: actions/checkout@v4
