name: Hello
on:
  push:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: ???
jobs:
  hello:
    name: 'First Action!'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          date
          ls
          pwd
          echo "hello, world! ${{inputs.greeting}}"
      - name: "context"
        run: |
          echo "${{ github.actor }}"
          echo "${{ env }}"
