name: Static Checking for Rails

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  static-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Rubocop
        run: bin/rubocop --fail-fast

      - name: Brakeman
        run: bundle exec brakeman -z -q

      - name: bundle audit
        run: bundle exec bundle audit check --update

      - name: Docker up
        run: docker compose up

      - name: rubocop 2
        run: docker compose run ror bin/rubocop --fail-fast

      - name: Brakeman 2
        run: docker compose run ror bundle exec brakeman -z -q

      - name: bundle audit 2
        run: docker compose run ror bundle exec bundle audit check --update
