name: Static checking in Ruby on Rails

on:
  push:
    branches: [ "master", "develop" ]
  schedule:
    - cron:  '0 0 1 * *' # 毎月一日に動作するようにする。

jobs:
  publishing:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - run: |
          gem install bundler
          bundle install
      - run: |
          ruby -v
      - run: |
          bin/rubocop
