name: Publishment

on:
  push:
    branches: [ "master", "develop" ]
  schedule:
    - cron:  '0 0 1 * *' # 毎月一日に動作するようにする。

jobs:
  publishing:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
      - run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
