name: Static Checking for Rails

on:
  concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  static-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    efaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Docker compose
        run: docker compose build

      - name: Rubocop
        run: bin/rubocop --fail-fast

      - name: Brakeman
        run: bundle exec brakeman -z -q

      - name: bundle audit
        run: bundle exec bundle audit check --update

      - name: rubocop 2
        run: docker compose exec ror bin/rubocop --fail-fast

      - name: Brakeman 2
        run: docker compose exec ror bundle exec brakeman -z -q

      - name: bundle audit 2
        run: docker compose exec ror bundle exec bundle audit check --update
